INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1234','Declan', 'Cordial');
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1235','Niall', 'Mulready' );
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1236', 'Ian', 'Cunningham');
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1237','Brendan', 'Greene');
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1238','Nicholas', 'Tsang' );
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1239', 'Sean', 'McGee');
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1240','Anthony', 'Shannon');
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1241','Conor', 'Harney' );
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1242', 'Decland', 'Horlick');
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1243','Joshua', 'Sherwood');
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1244','Bau', 'Nguyen' );
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1245', 'Kennedy', 'Bowers');
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1246', 'Daleel', 'Ramjan');
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1247', 'Ismael', 'Omar');


        